directories:
  output: release
  buildResources: build
appId: com.transport.metrics.dashboard
productName: Transport Metrics Dashboard
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - public/**/*
win:
  target:
    - target: dir
      arch:
        - x64
  icon: public/icon.png
  signAndEditExecutable: false
linux:
  target:
    - target: dir
      arch:
        - x64
  category: Utility
  icon: public/icon.png
forceCodeSigning: false
electronVersion: 28.3.3
